version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Set commit message preferences
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Set pull request labels
    labels:
      - "dependencies"
      - "python"
      - "ml"
    # Set reviewers
    reviewers:
      - "Maxime-Cllt"
    # Set assignees
    assignees:
      - "Maxime-Cllt"
    # Group ML/Data Science dependencies
    groups:
      ml-framework:
        patterns:
          - "torch*"
          - "tensorflow*"
          - "scikit-learn*"
          - "pandas*"
          - "numpy*"
          - "scipy*"
          - "matplotlib*"
          - "seaborn*"
          - "jupyter*"
          - "ipython*"
    target-branch: "main"
    versioning-strategy: "increase"