version: 2
updates:
  # Use pip ecosystem but configure for uv projects
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "ml"
      - "uv"
    reviewers:
      - "Maxime-Cllt"
    assignees:
      - "Maxime-Cllt"
    groups:
      ml-framework:
        patterns:
          - "torch*"
          - "scikit-learn*"
          - "pandas*"
          - "numpy*"
          - "scipy*"
          - "matplotlib*"
          - "seaborn*"
          - "transformers*"
          - "datasets*"
      dev-tools:
        patterns:
          - "pytest*"
          - "black*"
          - "ruff*"
    target-branch: "master"  # Your main branch
    versioning-strategy: "increase"