[build-system]
requires = ["setuptools>= 80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "DataLint-ml"
version = "1.0.0"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Maxime-Cllt" }
]
dependencies = [
    "torch>=2.7.0",
    "scikit-learn>=1.7.1",
    "pandas>=2.3.1",
    "numpy>=2.3.2",
]

[tool.setuptools.packages.find]
where = ["src"]
